### ISSUE TITLE
`$$props.class` doesn't work as expected

### ISSUE THREAD

**Issue by kayk1m** [coxwave/svelte-template#2]
Expected)
in `Item.svelte`
```svelte
<div class={$$props.class}>
  item!
</div>
```

in `index.svelte`
```svelte
<script>
  import Item from './Item.svelte'
</script>

<Item class="my-item" />

<style>
  /* Unused CSS selector ".my-item"svelte(css-unused-selector) */
  .my-item {
    color: red;
  }
</style>
```

**Comment by Jeonghyun-Kim** [comment]
### Related Thread

https://stackoverflow.com/questions/67049219/class-styling-on-a-custom-component-in-svelte-does-not-register

**Comment by Jeonghyun-Kim** [comment]
@kjsik11 How do you think of this topic?

**Comment by kjsik11** [comment]
[related issue](https://github.com/sveltejs/svelte/issues/2870)

**Comment by kjsik11** [comment]
Option 1 does not apply and option 2 works normally.
